[package]
name = "easytidy-gui"
version.workspace = true
description = "easytidy GUI manager"
authors = ["easytidy contributors"]
edition.workspace = true

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "easytidy_gui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["devtools"] }
tauri-plugin-opener = "2"
serde = { workspace = true }
serde_json = { workspace = true }
easytidy-core = { path = "../core" }
easytidy-protocol = { path = "../protocol" }
dirs = { workspace = true }
rfd = "0.15"
tokio = { workspace = true, features = ["full"] }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
futures = { workspace = true }
tokio-util = { workspace = true }
base64 = "0.22"
tracing-appender = "0.2.5"
