[package]
name = "easytidy-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
bollard = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
http-body-util = { workspace = true }
futures = { workspace = true }
uuid = { workspace = true }
tempfile = { workspace = true }
dirs = { workspace = true }
fs2 = { workspace = true }
chrono = { workspace = true }
